### ISSUE TITLE
[Bug] Hammers can break anything

### ISSUE THREAD

**Issue by ItzEnderArkail** [ErrorMikey/JustHammers#1]
even the lowest tier of hammer can break obsidian(aka stone hammer),

just a suggestion, make hammers mine slower than a pickaxe and not being able to break any other block that is not intended to be broken with a hammer(ex. dirt, wood, leaves)

**Comment by MichaelHillcox** [comment]
Not sure about not being able to break blocks that the tool would normally not be great against but I've just released a fix for the hammer being able to break things & get drops for blocks it should be able to break (iron hammer on a diamond ore for example)

**Comment by TheMockTv** [comment]
**[CRITICAL] Game-breaking crash with JustHammers – still present in 2025, known since 2022**

We are currently playing the modpack **FTB NeoTech (release: 2025-06-04)** via CurseForge and encountered a **severe crash** caused by JustHammers. It happens **every time** a player attempts to mine blocks using *any* hammer from the mod. The game immediately crashes with the following error:

The game crashed: exception in server tick loop
Error: java.lang.NoSuchMethodError: 'int pro.mikey.justhammers.neoforge.HammersPlatformImpl.getBlockXpAmount(net.minecraft.core.BlockPos, net.minecraft.world.level.block.state.BlockState, net.minecraft.world.level.Level, int, int)'


This crash was already reported in **2022** and has still not been fixed as of **July 2025**. This is not a minor bug – it renders the main function of the mod (mining with hammers) completely unusable and causes server instability.

We fully understand that this is a community-driven project, and that real-life time is limited. But a crash this fundamental, reported over three years ago, makes it impossible to use the mod in modern packs like FTB NeoTech.

### Suggestion:
- Please fix the method call that fails on XP calculation
- Or provide a config option to **disable XP output from hammers** as a workaround

Thank you for your work – we’d love to see this fixed so the mod can actually be played again.

**Comment by Sunekaer** [comment]
Please provide the version number of the mod, used in this modpack
